version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  check-linear:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: |
          [ 0 = "$(git rev-list --min-parents=2 --count "$(git merge-base master HEAD)"..HEAD)" ] && echo linear || (echo nonlinear branch git history && false)
workflows:
  version: 2
  workflow:
    jobs:
      - check-linear
      - build:
          filters:
            branches:
              only:
                - staging
                - trying
                - master
